site_name: 5GCloudWorks
docs_dir: docs
site_url: https://5gcloudworkslab.github.io/my-5g-lab-site/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  logo: logo.png

nav:
  - LAB_2 Codes: LAB2_codes.md
  - LAB_1 Codes: index.md
  - About: about.md

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search
